import { invoke } from '@tauri-apps/api/core';
import { listen, type UnlistenFn } from '@tauri-apps/api/event';
import { open, save } from '@tauri-apps/plugin-dialog';
import type { 
  ConnectionConfig, 
  QueryResult, 
  SchemaTree, 
  RelationEdge, 
  ExportJobRequest,
  ImportJobRequest,
  DbToDbTransferRequest,
  TransferProgressEvent,
  FileInspectionResult
} from './types';

// Check if running in Tauri environment
const isTauri = typeof window !== 'undefined' && '__TAURI_INTERNALS__' in window;

export const api = {
  // Connection commands
  async testConnection(config: ConnectionConfig): Promise<{ success: boolean; message: string; latencyMs: number }> {
    if (isTauri) {
      return await invoke('test_connection', { config });
    }
    // Browser Mock for instant dev preview
    await new Promise(r => setTimeout(r, 200));
    return { success: true, message: 'Connected successfully (Mock Mode)', latencyMs: 14 };
  },

  async connect(config: ConnectionConfig): Promise<void> {
    if (isTauri) {
      return await invoke('connect_database', { config });
    }
    console.log('[Mock API] Connected to:', config.name);
  },

  async disconnect(connectionId: string): Promise<void> {
    if (isTauri) {
      return await invoke('disconnect_database', { connectionId });
    }
    console.log('[Mock API] Disconnected:', connectionId);
  },

  // Schema commands
  async fetchSchema(connectionId: string): Promise<SchemaTree> {
    if (isTauri) {
      return await invoke('fetch_schema_tree', { connectionId });
    }
    return {
      databases: ['fugdb_test'],
      currentDatabase: 'fugdb_test',
      tables: [
        { schema: 'public', name: 'users', tableType: 'table', rowCountEstimate: 1200 },
        { schema: 'public', name: 'orders', tableType: 'table', rowCountEstimate: 45000 },
        { schema: 'public', name: 'order_items', tableType: 'table', rowCountEstimate: 120000 },
        { schema: 'public', name: 'products', tableType: 'table', rowCountEstimate: 340 },
        { schema: 'public', name: 'audit_logs', tableType: 'table', rowCountEstimate: 89000 },
      ]
    };
  },

  async generateErdMetadata(connectionId: string): Promise<RelationEdge[]> {
    if (isTauri) {
      return await invoke('generate_erd_metadata', { connectionId });
    }
    return [
      { id: 'e1', fromTable: 'orders', fromColumn: 'user_id', toTable: 'users', toColumn: 'id' },
      { id: 'e2', fromTable: 'order_items', fromColumn: 'order_id', toTable: 'orders', toColumn: 'id' },
      { id: 'e3', fromTable: 'order_items', fromColumn: 'product_id', toTable: 'products', toColumn: 'id' }
    ];
  },

  async generateDataDictionary(connectionId: string, format: 'markdown' | 'html' | 'json'): Promise<string> {
    if (isTauri) {
      return await invoke('generate_data_dictionary', { connectionId, format });
    }
    if (format === 'html') {
      return `<!DOCTYPE html><html><body><h1>Data Dictionary (Mock)</h1><p>Demo documentation for ${connectionId}</p></body></html>`;
    }
    if (format === 'json') {
      return JSON.stringify({ database: connectionId, tables: [] }, null, 2);
    }
    return `# 📚 Database Schema Documentation: ${connectionId}\n\n*Generated by FugDB Data Dictionary Engine*`;
  },

  async exportDataDictionaryFile(connectionId: string, format: 'markdown' | 'html' | 'json', targetPath: string): Promise<string> {
    if (isTauri) {
      return await invoke('export_data_dictionary_file', { connectionId, format, targetPath });
    }
    return targetPath;
  },

  async printDataDictionary(connectionId: string): Promise<string> {
    if (isTauri) {
      return await invoke('print_data_dictionary', { connectionId });
    }
    window.print();
    return 'mock_print_path';
  },

  // Query commands
  async executeQuery(connectionId: string, sql: string, pageSize?: number, offset?: number): Promise<QueryResult> {
    if (isTauri) {
      return await invoke('execute_query', { connectionId, sql, pageSize, offset });
    }
    
    // Realistic browser mock result
    await new Promise(r => setTimeout(r, 60));
    return {
      columns: [
        { name: 'id', dataType: 'int4', isPrimaryKey: true, isForeignKey: false, nullable: false },
        { name: 'name', dataType: 'varchar', isPrimaryKey: false, isForeignKey: false, nullable: false },
        { name: 'email', dataType: 'varchar', isPrimaryKey: false, isForeignKey: false, nullable: false },
        { name: 'role', dataType: 'varchar', isPrimaryKey: false, isForeignKey: false, nullable: true },
        { name: 'is_active', dataType: 'bool', isPrimaryKey: false, isForeignKey: false, nullable: false },
        { name: 'created_at', dataType: 'timestamptz', isPrimaryKey: false, isForeignKey: false, nullable: false },
      ],
      rows: [
        [1, 'Aditya Pratama', 'aditya@fugdb.dev', 'admin', true, '2026-09-30T10:15:00Z'],
        [2, 'Jane Doe', 'jane@example.com', 'developer', true, '2026-09-30T10:20:00Z'],
        [3, 'John Smith', 'john@example.com', 'qa', false, '2026-09-30T10:25:00Z'],
        [4, 'Alice Wonder', 'alice@matrix.io', 'analyst', true, '2026-09-30T11:00:00Z'],
        [5, 'Bob Builder', 'bob@construct.dev', 'member', true, '2026-09-30T11:30:00Z'],
      ],
      affectedRows: 5,
      executionTimeMs: 4.2,
      totalRows: 5,
    };
  },

  // Mock data batch generator
  async generateMockBatch(connectionId: string, table: string, count: number): Promise<number> {
    if (isTauri) {
      return await invoke('generate_mock_batch', { connectionId, table, count });
    }
    await new Promise(r => setTimeout(r, 350));
    return count;
  },

  // Transfer & ETL Engine API
  async inspectFile(path: string): Promise<FileInspectionResult> {
    if (isTauri) {
      return await invoke('inspect_file', { path });
    }
    return {
      detectedFormat: path.endsWith('.json') ? 'json' : path.endsWith('.xlsx') ? 'excel' : 'csv',
      delimiter: ',',
      hasHeader: true,
      columns: ['id', 'name', 'email', 'status', 'created_at'],
      sampleRows: [
        [1, 'Aditya', 'aditya@fugdb.dev', 'active', '2026-09-30'],
        [2, 'Budi', 'budi@example.com', 'pending', '2026-09-30'],
      ],
      totalBytes: 1024 * 450,
    };
  },

  async startExportJob(request: ExportJobRequest): Promise<string> {
    if (isTauri) {
      return await invoke('start_export_job', { request });
    }
    return 'mock_export_job_1';
  },

  async startImportJob(request: ImportJobRequest): Promise<string> {
    if (isTauri) {
      return await invoke('start_import_job', { request });
    }
    return 'mock_import_job_1';
  },

  async startDbToDbTransfer(request: DbToDbTransferRequest): Promise<string> {
    if (isTauri) {
      return await invoke('start_db_to_db_job', { request });
    }
    return 'mock_db2db_job_1';
  },

  async cancelTransferJob(jobId: string): Promise<boolean> {
    if (isTauri) {
      return await invoke('cancel_transfer_job', { jobId });
    }
    return true;
  },

  async onTransferProgress(callback: (event: TransferProgressEvent) => void): Promise<UnlistenFn> {
    if (isTauri) {
      return await listen<TransferProgressEvent>('transfer-progress', (e) => {
        callback(e.payload);
      });
    }
    return () => {};
  },

  // Native File Pickers via Dialog Plugin
  async pickOpenFile(filters?: { name: string; extensions: string[] }[]): Promise<string | null> {
    if (isTauri) {
      const selected = await open({
        multiple: false,
        directory: false,
        filters: filters || [
          { name: 'All Data Files', extensions: ['csv', 'tsv', 'json', 'ndjson', 'xlsx', 'sql'] },
          { name: 'CSV & TSV Files', extensions: ['csv', 'tsv'] },
          { name: 'JSON & NDJSON', extensions: ['json', 'ndjson', 'jsonl'] },
          { name: 'Excel Spreadsheets', extensions: ['xlsx', 'xls'] },
          { name: 'SQL Scripts', extensions: ['sql'] },
        ],
      });
      return selected as string | null;
    }
    return '/Users/fugdb/data/sample_dataset.csv';
  },

  async pickSaveFile(defaultName?: string, filters?: { name: string; extensions: string[] }[]): Promise<string | null> {
    if (isTauri) {
      const selected = await save({
        defaultPath: defaultName || 'export_data.csv',
        filters: filters || [
          { name: 'CSV Comma Separated', extensions: ['csv'] },
          { name: 'TSV Tab Separated', extensions: ['tsv'] },
          { name: 'JSON Document', extensions: ['json'] },
          { name: 'JSON Lines (ndjson)', extensions: ['ndjson'] },
          { name: 'Excel Spreadsheet', extensions: ['xlsx'] },
          { name: 'SQL Dump Script', extensions: ['sql'] },
        ],
      });
      return selected as string | null;
    }
    return `/Users/fugdb/downloads/${defaultName || 'export_data.csv'}`;
  },
};
