import { invoke } from '@tauri-apps/api/core';
import { listen, type UnlistenFn } from '@tauri-apps/api/event';
import { open, save } from '@tauri-apps/plugin-dialog';
import type { 
  ConnectionConfig, 
  QueryResult, 
  SchemaTree, 
  RelationEdge, 
  ExportJobRequest,
  ImportJobRequest,
  DbToDbTransferRequest,
  TransferProgressEvent,
  FileInspectionResult,
  ColumnMockRule,
  TableMockInspection,
  MockBatchResult,
  AiProviderConfig,
  AiSqlResponse,
  OllamaModelInfo,
  ExplainResult,
  ServerProcess,
  ServerHealthStats,
  SchemaDiffResult,
  RedisKeyItem,
  RedisScanResult,
  RedisKeyDetail,
  RedisZSetMember,
  RedisStreamEntry,
  RedisServerInfo,
  RedisCliResponse
} from './types';

// Check if running in Tauri environment
const isTauri = typeof window !== 'undefined' && '__TAURI_INTERNALS__' in window;

export const api = {
  // Connection commands
  async testConnection(config: ConnectionConfig): Promise<{ success: boolean; message: string; latencyMs: number }> {
    if (isTauri) {
      return await invoke('test_connection', { config });
    }
    // Browser Mock for instant dev preview
    await new Promise(r => setTimeout(r, 200));
    return { success: true, message: 'Connected successfully (Mock Mode)', latencyMs: 14 };
  },

  async testSshTunnel(config: ConnectionConfig): Promise<{ success: boolean; message: string; latencyMs: number }> {
    if (isTauri) {
      return await invoke('test_ssh_tunnel', { config });
    }
    // Browser Mock
    await new Promise(r => setTimeout(r, 200));
    return { 
      success: true, 
      message: `SSH Bastion Host handshake succeeded for user '${config.sshUser || 'ubuntu'}' on ${config.sshHost || 'bastion'}! (Mock Mode)`, 
      latencyMs: 22 
    };
  },

  async connect(config: ConnectionConfig): Promise<void> {
    if (isTauri) {
      return await invoke('connect_database', { config });
    }
    console.log('[Mock API] Connected to:', config.name);
  },

  async disconnect(connectionId: string): Promise<void> {
    if (isTauri) {
      return await invoke('disconnect_database', { connectionId });
    }
    console.log('[Mock API] Disconnected:', connectionId);
  },

  // OS Keyring Credentials API
  async saveKeyringCredential(key: string, secret: string): Promise<void> {
    if (isTauri) {
      return await invoke('save_keyring_credential', { key, secret });
    }
    try {
      sessionStorage.setItem(`mock_keyring_${key}`, secret);
    } catch {}
  },

  async getKeyringCredential(key: string): Promise<string | null> {
    if (isTauri) {
      return await invoke('get_keyring_credential', { key });
    }
    try {
      return sessionStorage.getItem(`mock_keyring_${key}`);
    } catch {
      return null;
    }
  },

  async deleteKeyringCredential(key: string): Promise<boolean> {
    if (isTauri) {
      return await invoke('delete_keyring_credential', { key });
    }
    try {
      sessionStorage.removeItem(`mock_keyring_${key}`);
      return true;
    } catch {
      return false;
    }
  },

  // Schema commands
  async fetchSchema(connectionId: string): Promise<SchemaTree> {
    if (isTauri) {
      return await invoke('fetch_schema_tree', { connectionId });
    }
    return {
      databases: ['fugdb_test'],
      currentDatabase: 'fugdb_test',
      tables: [
        { schema: 'public', name: 'users', tableType: 'table', rowCountEstimate: 1200 },
        { schema: 'public', name: 'orders', tableType: 'table', rowCountEstimate: 45000 },
        { schema: 'public', name: 'order_items', tableType: 'table', rowCountEstimate: 120000 },
        { schema: 'public', name: 'products', tableType: 'table', rowCountEstimate: 340 },
        { schema: 'public', name: 'audit_logs', tableType: 'table', rowCountEstimate: 89000 },
      ]
    };
  },

  async generateErdMetadata(connectionId: string): Promise<RelationEdge[]> {
    if (isTauri) {
      return await invoke('generate_erd_metadata', { connectionId });
    }
    return [
      { id: 'e1', fromTable: 'orders', fromColumn: 'user_id', toTable: 'users', toColumn: 'id' },
      { id: 'e2', fromTable: 'order_items', fromColumn: 'order_id', toTable: 'orders', toColumn: 'id' },
      { id: 'e3', fromTable: 'order_items', fromColumn: 'product_id', toTable: 'products', toColumn: 'id' }
    ];
  },

  async generateDataDictionary(connectionId: string, format: 'markdown' | 'html' | 'json'): Promise<string> {
    if (isTauri) {
      return await invoke('generate_data_dictionary', { connectionId, format });
    }
    if (format === 'html') {
      return `<!DOCTYPE html><html><body><h1>Data Dictionary (Mock)</h1><p>Demo documentation for ${connectionId}</p></body></html>`;
    }
    if (format === 'json') {
      return JSON.stringify({ database: connectionId, tables: [] }, null, 2);
    }
    return `# 📚 Database Schema Documentation: ${connectionId}\n\n*Generated by FugDB Data Dictionary Engine*`;
  },

  async exportDataDictionaryFile(connectionId: string, format: 'markdown' | 'html' | 'json', targetPath: string): Promise<string> {
    if (isTauri) {
      return await invoke('export_data_dictionary_file', { connectionId, format, targetPath });
    }
    return targetPath;
  },

  async printDataDictionary(connectionId: string): Promise<string> {
    if (isTauri) {
      return await invoke('print_data_dictionary', { connectionId });
    }
    window.print();
    return 'mock_print_path';
  },

  // Query commands
  async executeQuery(connectionId: string, sql: string, pageSize?: number, offset?: number): Promise<QueryResult> {
    if (isTauri) {
      return await invoke('execute_query', { connectionId, sql, pageSize, offset });
    }
    
    // Realistic browser mock result
    await new Promise(r => setTimeout(r, 60));
    return {
      columns: [
        { name: 'id', dataType: 'int4', isPrimaryKey: true, isForeignKey: false, nullable: false },
        { name: 'name', dataType: 'varchar', isPrimaryKey: false, isForeignKey: false, nullable: false },
        { name: 'email', dataType: 'varchar', isPrimaryKey: false, isForeignKey: false, nullable: false },
        { name: 'role', dataType: 'varchar', isPrimaryKey: false, isForeignKey: false, nullable: true },
        { name: 'is_active', dataType: 'bool', isPrimaryKey: false, isForeignKey: false, nullable: false },
        { name: 'created_at', dataType: 'timestamptz', isPrimaryKey: false, isForeignKey: false, nullable: false },
      ],
      rows: [
        [1, 'Aditya Pratama', 'aditya@fugdb.dev', 'admin', true, '2026-09-30T10:15:00Z'],
        [2, 'Jane Doe', 'jane@example.com', 'developer', true, '2026-09-30T10:20:00Z'],
        [3, 'John Smith', 'john@example.com', 'qa', false, '2026-09-30T10:25:00Z'],
        [4, 'Alice Wonder', 'alice@matrix.io', 'analyst', true, '2026-09-30T11:00:00Z'],
        [5, 'Bob Builder', 'bob@construct.dev', 'member', true, '2026-09-30T11:30:00Z'],
      ],
      affectedRows: 5,
      executionTimeMs: 4.2,
      totalRows: 5,
    };
  },

  async beginTransaction(connectionId: string, driver?: string): Promise<QueryResult> {
    if (isTauri) {
      return await invoke('begin_transaction', { connectionId, driver });
    }
    await new Promise(r => setTimeout(r, 40));
    return { columns: [], rows: [], affectedRows: 0, executionTimeMs: 1.2 };
  },

  async commitTransaction(connectionId: string, driver?: string): Promise<QueryResult> {
    if (isTauri) {
      return await invoke('commit_transaction', { connectionId, driver });
    }
    await new Promise(r => setTimeout(r, 40));
    return { columns: [], rows: [], affectedRows: 0, executionTimeMs: 1.4 };
  },

  async rollbackTransaction(connectionId: string, driver?: string): Promise<QueryResult> {
    if (isTauri) {
      return await invoke('rollback_transaction', { connectionId, driver });
    }
    await new Promise(r => setTimeout(r, 40));
    return { columns: [], rows: [], affectedRows: 0, executionTimeMs: 1.1 };
  },

  // Smart QA Mock Data Generator API
  async inspectTableMockConfig(connectionId: string, tableName: string): Promise<TableMockInspection> {
    if (isTauri) {
      return await invoke('inspect_table_mock_config', { connectionId, tableName });
    }
    // Mock for browser testing
    return {
      tableName,
      columns: [
        { columnName: 'id', dataType: 'int4', isPrimaryKey: true, isForeignKey: false, nullable: false, include: false, generatorType: 'auto_increment', nullPercentage: 0 },
        { columnName: 'name', dataType: 'varchar', isPrimaryKey: false, isForeignKey: false, nullable: false, include: true, generatorType: 'full_name', nullPercentage: 0 },
        { columnName: 'email', dataType: 'varchar', isPrimaryKey: false, isForeignKey: false, nullable: false, include: true, generatorType: 'email', nullPercentage: 0 },
        { columnName: 'phone', dataType: 'varchar', isPrimaryKey: false, isForeignKey: false, nullable: true, include: true, generatorType: 'phone', nullPercentage: 10 },
        { columnName: 'role', dataType: 'varchar', isPrimaryKey: false, isForeignKey: false, nullable: false, include: true, generatorType: 'custom_list', customOptions: 'admin, editor, viewer, qa', nullPercentage: 0 },
        { columnName: 'is_active', dataType: 'bool', isPrimaryKey: false, isForeignKey: false, nullable: false, include: true, generatorType: 'boolean', nullPercentage: 0 },
        { columnName: 'created_at', dataType: 'timestamptz', isPrimaryKey: false, isForeignKey: false, nullable: false, include: true, generatorType: 'timestamp_past', nullPercentage: 0 },
      ]
    };
  },

  async previewMockRows(rules: ColumnMockRule[], count: number = 10): Promise<Record<string, any>[]> {
    if (isTauri) {
      return await invoke('preview_mock_rows', { rules, count });
    }
    return Array.from({ length: count }, (_, i) => ({
      name: `User ${i + 1}`,
      email: `user${i + 1}@example.com`,
      phone: `+62-812-${1000 + i}-4455`,
      role: 'developer',
      is_active: true,
      created_at: '2026-09-30 12:00:00'
    }));
  },

  async generateMockSqlScript(tableName: string, rules: ColumnMockRule[], count: number = 100): Promise<string> {
    if (isTauri) {
      return await invoke('generate_mock_sql_script', { tableName, rules, count });
    }
    return `-- Smart QA Mock Data Script for \`${tableName}\`\nINSERT INTO ${tableName} (name, email) VALUES ('Demo User', 'demo@fugdb.dev');`;
  },

  async executeMockBatchInsert(
    connectionId: string, 
    tableName: string, 
    rules: ColumnMockRule[], 
    count: number, 
    chunkSize?: number,
    truncateFirst?: boolean,
    conflictStrategy?: string
  ): Promise<MockBatchResult> {
    if (isTauri) {
      return await invoke('execute_mock_batch_insert', { 
        connectionId, 
        tableName, 
        rules, 
        count, 
        chunkSize,
        truncateFirst,
        conflictStrategy
      });
    }
    await new Promise(r => setTimeout(r, 600));
    return {
      insertedRows: count,
      executionTimeMs: 42.5,
      chunksCount: Math.ceil(count / 250),
      tableName
    };
  },

  async generateMockBatch(connectionId: string, table: string, count: number): Promise<number> {
    if (isTauri) {
      return await invoke('generate_mock_batch', { connectionId, table, count });
    }
    await new Promise(r => setTimeout(r, 350));
    return count;
  },

  // Transfer & ETL Engine API
  async inspectFile(path: string): Promise<FileInspectionResult> {
    if (isTauri) {
      return await invoke('inspect_file', { path });
    }
    return {
      detectedFormat: path.endsWith('.json') ? 'json' : path.endsWith('.xlsx') ? 'excel' : 'csv',
      delimiter: ',',
      hasHeader: true,
      columns: ['id', 'name', 'email', 'status', 'created_at'],
      sampleRows: [
        [1, 'Aditya', 'aditya@fugdb.dev', 'active', '2026-09-30'],
        [2, 'Budi', 'budi@example.com', 'pending', '2026-09-30'],
      ],
      totalBytes: 1024 * 450,
    };
  },

  async startExportJob(request: ExportJobRequest): Promise<string> {
    if (isTauri) {
      return await invoke('start_export_job', { request });
    }
    return 'mock_export_job_1';
  },

  async startImportJob(request: ImportJobRequest): Promise<string> {
    if (isTauri) {
      return await invoke('start_import_job', { request });
    }
    return 'mock_import_job_1';
  },

  async startDbToDbTransfer(request: DbToDbTransferRequest): Promise<string> {
    if (isTauri) {
      return await invoke('start_db_to_db_job', { request });
    }
    return 'mock_db2db_job_1';
  },

  async cancelTransferJob(jobId: string): Promise<boolean> {
    if (isTauri) {
      return await invoke('cancel_transfer_job', { jobId });
    }
    return true;
  },

  async onTransferProgress(callback: (event: TransferProgressEvent) => void): Promise<UnlistenFn> {
    if (isTauri) {
      return await listen<TransferProgressEvent>('transfer-progress', (e) => {
        callback(e.payload);
      });
    }
    return () => {};
  },

  // Native File Pickers via Dialog Plugin
  async pickOpenFile(filters?: { name: string; extensions: string[] }[]): Promise<string | null> {
    if (isTauri) {
      const selected = await open({
        multiple: false,
        directory: false,
        filters: filters || [
          { name: 'All Data Files', extensions: ['csv', 'tsv', 'json', 'ndjson', 'xlsx', 'sql'] },
          { name: 'CSV & TSV Files', extensions: ['csv', 'tsv'] },
          { name: 'JSON & NDJSON', extensions: ['json', 'ndjson', 'jsonl'] },
          { name: 'Excel Spreadsheets', extensions: ['xlsx', 'xls'] },
          { name: 'SQL Scripts', extensions: ['sql'] },
        ],
      });
      return selected as string | null;
    }
    return '/Users/fugdb/data/sample_dataset.csv';
  },

  async pickSaveFile(defaultName?: string, filters?: { name: string; extensions: string[] }[]): Promise<string | null> {
    if (isTauri) {
      const selected = await save({
        defaultPath: defaultName || 'export_data.csv',
        filters: filters || [
          { name: 'CSV Comma Separated', extensions: ['csv'] },
          { name: 'TSV Tab Separated', extensions: ['tsv'] },
          { name: 'JSON Document', extensions: ['json'] },
          { name: 'JSON Lines (ndjson)', extensions: ['ndjson'] },
          { name: 'Excel Spreadsheet', extensions: ['xlsx'] },
          { name: 'SQL Dump Script', extensions: ['sql'] },
        ],
      });
      return selected as string | null;
    }
    return `/Users/fugdb/downloads/${defaultName || 'export_data.csv'}`;
  },

  async saveImageFile(targetPath: string, base64Data: string): Promise<string> {
    if (isTauri) {
      return await invoke('save_image_file', { targetPath, base64Data });
    }
    return targetPath;
  },

  // AI Copilot & NL-to-SQL API
  async testAiConnection(config: AiProviderConfig): Promise<string> {
    if (isTauri) {
      return await invoke('test_ai_connection', { config });
    }
    await new Promise(r => setTimeout(r, 400));
    return `Successfully connected to ${config.provider}!`;
  },

  async listOllamaModels(endpoint?: string): Promise<OllamaModelInfo[]> {
    if (isTauri) {
      return await invoke('list_ollama_models', { endpoint });
    }
    return [
      { name: 'qwen2.5-coder:latest', size: 4500000000, modifiedAt: '2026-10-01T10:00:00Z' },
      { name: 'llama3.2:latest', size: 2000000000, modifiedAt: '2026-10-02T10:00:00Z' },
      { name: 'sqlcoder:latest', size: 4100000000, modifiedAt: '2026-09-28T10:00:00Z' },
    ];
  },

  async generateSqlFromPrompt(
    connectionId: string,
    config: AiProviderConfig,
    userPrompt: string,
    selectedTables?: string[],
    driver?: string
  ): Promise<AiSqlResponse> {
    if (isTauri) {
      return await invoke('generate_sql_from_prompt', {
        connectionId,
        config,
        userPrompt,
        selectedTables,
        driver
      });
    }
    await new Promise(r => setTimeout(r, 800));
    return {
      sql: `SELECT u.id, u.name, u.email, COUNT(o.id) AS total_orders, COALESCE(SUM(o.total_amount), 0) AS lifetime_value\nFROM users u\nLEFT JOIN orders o ON u.id = o.user_id\nWHERE u.status = 'active'\nGROUP BY u.id, u.name, u.email\nORDER BY lifetime_value DESC\nLIMIT 10;`,
      explanation: `1. Joins the \`users\` table with \`orders\` on \`user_id\`.\n2. Filters active users.\n3. Aggregates order count and sum of total_amount.\n4. Sorts by highest lifetime value and limits to top 10.`,
      tablesUsed: ['users', 'orders'],
      dialect: driver || 'PostgreSQL',
      modelUsed: config.model,
      executionTimeMs: 342.1
    };
  },

  async fixSqlError(
    connectionId: string,
    config: AiProviderConfig,
    sql: string,
    errorMessage: string,
    driver?: string
  ): Promise<AiSqlResponse> {
    if (isTauri) {
      return await invoke('fix_sql_error', {
        connectionId,
        config,
        sql,
        errorMessage,
        driver
      });
    }
    await new Promise(r => setTimeout(r, 700));
    return {
      sql: `-- Fixed Query\nSELECT * FROM users WHERE email ILIKE '%@gmail.com';`,
      explanation: `Corrected column name syntax and adjusted case-insensitive comparison operator for ${driver || 'PostgreSQL'}.`,
      tablesUsed: ['users'],
      dialect: driver || 'PostgreSQL',
      modelUsed: config.model,
      executionTimeMs: 280.0
    };
  },

  async explainQuery(
    connectionId: string,
    sql: string,
    analyze: boolean = true,
    driver?: string
  ): Promise<ExplainResult> {
    if (isTauri) {
      return await invoke('explain_query', {
        connectionId,
        sql,
        analyze,
        driver
      });
    }
    await new Promise(r => setTimeout(r, 450));
    
    // Mock Postgres JSON Plan for browser demo
    const mockJsonPlan = [
      {
        "Plan": {
          "Node Type": "Hash Join",
          "Parallel Aware": false,
          "Async Capable": false,
          "Join Type": "Inner",
          "Startup Cost": 25.50,
          "Total Cost": 142.80,
          "Plan Rows": 1250,
          "Plan Width": 64,
          "Actual Startup Time": 0.42,
          "Actual Total Time": 3.85,
          "Actual Rows": 1200,
          "Actual Loops": 1,
          "Hash Cond": "(o.user_id = u.id)",
          "Shared Hit Blocks": 42,
          "Shared Read Blocks": 0,
          "Plans": [
            {
              "Node Type": "Seq Scan",
              "Parent Relationship": "Outer",
              "Parallel Aware": false,
              "Async Capable": false,
              "Relation Name": "orders",
              "Alias": "o",
              "Startup Cost": 0.00,
              "Total Cost": 65.00,
              "Plan Rows": 4500,
              "Plan Width": 32,
              "Actual Startup Time": 0.02,
              "Actual Total Time": 1.25,
              "Actual Rows": 4500,
              "Actual Loops": 1,
              "Filter": "(total_amount > 100.00)",
              "Rows Removed by Filter": 350,
              "Shared Hit Blocks": 28
            },
            {
              "Node Type": "Hash",
              "Parent Relationship": "Inner",
              "Parallel Aware": false,
              "Async Capable": false,
              "Startup Cost": 15.00,
              "Total Cost": 15.00,
              "Plan Rows": 1200,
              "Plan Width": 32,
              "Actual Startup Time": 0.35,
              "Actual Total Time": 0.35,
              "Actual Rows": 1200,
              "Actual Loops": 1,
              "Hash Buckets": 2048,
              "Hash Batches": 1,
              "Original Hash Batches": 1,
              "Peak Memory Usage": 85,
              "Plans": [
                {
                  "Node Type": "Index Scan",
                  "Parent Relationship": "Outer",
                  "Parallel Aware": false,
                  "Async Capable": false,
                  "Index Name": "users_pkey",
                  "Relation Name": "users",
                  "Alias": "u",
                  "Startup Cost": 0.28,
                  "Total Cost": 15.00,
                  "Plan Rows": 1200,
                  "Plan Width": 32,
                  "Actual Startup Time": 0.04,
                  "Actual Total Time": 0.28,
                  "Actual Rows": 1200,
                  "Actual Loops": 1,
                  "Index Cond": "(id IS NOT NULL)",
                  "Shared Hit Blocks": 14
                }
              ]
            }
          ]
        },
        "Planning Time": 0.34,
        "Execution Time": 4.12
      }
    ];

    return {
      rawPlan: JSON.stringify(mockJsonPlan, null, 2),
      jsonPlan: mockJsonPlan,
      queryResult: {
        columns: [{ name: 'QUERY PLAN', dataType: 'json', isPrimaryKey: false, isForeignKey: false, nullable: false }],
        rows: [[JSON.stringify(mockJsonPlan)]],
        affectedRows: 1,
        executionTimeMs: 4.12
      },
      executionTimeMs: 4.12,
      planningTimeMs: 0.34,
      dialect: driver || 'PostgreSQL',
      hasAnalyze: analyze
    };
  },

  async optimizeQueryExplain(
    connectionId: string,
    config: AiProviderConfig,
    sql: string,
    explainPlan: string,
    driver?: string
  ): Promise<AiSqlResponse> {
    if (isTauri) {
      return await invoke('optimize_query_explain', {
        connectionId,
        config,
        sql,
        explainPlan,
        driver
      });
    }
    await new Promise(r => setTimeout(r, 900));
    return {
      sql: `-- Recommended Indexes:\nCREATE INDEX idx_orders_user_amount ON orders (user_id, total_amount);\n\n-- Optimized Query:\nSELECT u.id, u.name, o.id AS order_id, o.total_amount\nFROM users u\nJOIN orders o ON u.id = o.user_id\nWHERE o.total_amount > 100.00;`,
      explanation: `1. **Sequential Scan Bottleneck Detected**: The \`orders\` table scan spent significant execution time filtering \`total_amount > 100.00\`.\n2. **Composite Index Recommendation**: Creating \`idx_orders_user_amount\` eliminates the Seq Scan and converts the join into an Index Scan with direct filter pushdown.\n3. **Memory & I/O Reduction**: Expected cost drops from ~142.80 to ~18.50 with 0 buffer misses.`,
      tablesUsed: ['orders', 'users'],
      dialect: driver || 'PostgreSQL',
      modelUsed: config.model,
      executionTimeMs: 420.0
    };
  },

  // 5.1 Live Server Health & Active Process Monitor API
  async getServerProcesses(connectionId: string, driver?: string): Promise<ServerHealthStats> {
    if (isTauri) {
      return await invoke('get_server_processes', { connectionId, driver });
    }
    // Realistic browser mock data for preview/dev mode
    await new Promise(r => setTimeout(r, 60));
    return {
      activeConnections: 3,
      idleConnections: 12,
      totalConnections: 16,
      maxConnections: 100,
      uptimeSeconds: 86400 * 3,
      version: 'PostgreSQL 16.2 (Debian 16.2-1.pgdg120+1)',
      processes: [
        {
          pid: '4128',
          user: 'postgres',
          database: 'production_db',
          clientAddr: '192.168.1.104:54322',
          applicationName: 'fugdb_app',
          state: 'active',
          query: 'SELECT u.id, u.name, count(o.id) FROM users u LEFT JOIN orders o ON u.id = o.user_id GROUP BY u.id, u.name ORDER BY count(o.id) DESC LIMIT 50;',
          durationSeconds: 0.12,
          waitEvent: 'ClientRead',
          startedAt: '2026-10-03 20:35:10'
        },
        {
          pid: '5890',
          user: 'analytics_bot',
          database: 'production_db',
          clientAddr: '10.0.4.12:48910',
          applicationName: 'etl_worker',
          state: 'active',
          query: 'REFRESH MATERIALIZED VIEW CONCURRENTLY mv_monthly_revenue_summary;',
          durationSeconds: 42.85,
          waitEvent: 'IO: DataFileRead',
          startedAt: '2026-10-03 20:34:28'
        },
        {
          pid: '6211',
          user: 'app_backend',
          database: 'production_db',
          clientAddr: '10.0.2.15:51200',
          applicationName: 'node_service',
          state: 'idle in transaction',
          query: 'UPDATE payments SET status = \'processing\' WHERE id = 98124;',
          durationSeconds: 14.50,
          waitEvent: 'Lock: transactionid',
          startedAt: '2026-10-03 20:34:56'
        },
        {
          pid: '6245',
          user: 'app_backend',
          database: 'production_db',
          clientAddr: '10.0.2.18:51204',
          applicationName: 'node_service',
          state: 'waiting',
          query: 'SELECT * FROM payments WHERE id = 98124 FOR UPDATE;',
          durationSeconds: 8.20,
          waitEvent: 'Lock: tuple',
          blockedBy: '6211',
          startedAt: '2026-10-03 20:35:02'
        },
        {
          pid: '3012',
          user: 'readonly_user',
          database: 'production_db',
          clientAddr: '192.168.1.45:41002',
          applicationName: 'metabase',
          state: 'idle',
          query: 'SELECT 1;',
          durationSeconds: 0.0,
          startedAt: '2026-10-03 20:30:00'
        }
      ],
      summaryCounts: {
        active: 2,
        'idle in transaction': 1,
        waiting: 1,
        idle: 12
      }
    };
  },

  async killServerProcess(connectionId: string, pid: string, driver?: string): Promise<boolean> {
    if (isTauri) {
      return await invoke('kill_server_process', { connectionId, pid, driver });
    }
    await new Promise(r => setTimeout(r, 60));
    return true;
  },

  async cancelServerQuery(connectionId: string, pid: string, driver?: string): Promise<boolean> {
    if (isTauri) {
      return await invoke('cancel_server_query', { connectionId, pid, driver });
    }
    await new Promise(r => setTimeout(r, 60));
    return true;
  },

  // 5.2 Schema & Data Diff Sync API
  async compareSchemas(
    sourceConnectionId: string,
    targetConnectionId: string,
    sourceDriver?: string,
    targetDriver?: string
  ): Promise<SchemaDiffResult> {
    if (isTauri) {
      return await invoke('compare_schemas', {
        sourceConnectionId,
        targetConnectionId,
        sourceDriver,
        targetDriver,
      });
    }

    // Realistic browser mock data for preview/dev mode
    await new Promise(r => setTimeout(r, 120));
    return {
      sourceConnectionId,
      targetConnectionId,
      sourceDriver: sourceDriver || 'PostgreSQL',
      targetDriver: targetDriver || 'PostgreSQL',
      totalSourceTables: 6,
      totalTargetTables: 4,
      tablesToCreate: 2,
      tablesToDrop: 0,
      tablesToAlter: 2,
      tablesIdentical: 2,
      tableDiffs: [
        {
          tableName: 'audit_logs',
          action: 'create',
          sourceRowCount: 1420,
          targetRowCount: undefined,
          columns: [
            { name: 'id', action: 'create', sourceType: 'bigint', sourceNullable: false, sourcePk: true, diffReason: 'Table missing in target' },
            { name: 'user_id', action: 'create', sourceType: 'int4', sourceNullable: false, sourcePk: false, diffReason: 'Table missing in target' },
            { name: 'action', action: 'create', sourceType: 'varchar', sourceNullable: false, sourcePk: false, diffReason: 'Table missing in target' },
            { name: 'created_at', action: 'create', sourceType: 'timestamptz', sourceNullable: false, sourcePk: false, diffReason: 'Table missing in target' }
          ],
          syncSql: `CREATE TABLE "audit_logs" (\n  "id" BIGINT NOT NULL,\n  "user_id" INTEGER NOT NULL,\n  "action" VARCHAR NOT NULL,\n  "created_at" TIMESTAMPTZ NOT NULL,\n  PRIMARY KEY ("id")\n);`
        },
        {
          tableName: 'user_profiles',
          action: 'create',
          sourceRowCount: 820,
          targetRowCount: undefined,
          columns: [
            { name: 'user_id', action: 'create', sourceType: 'int4', sourceNullable: false, sourcePk: true, diffReason: 'Table missing in target' },
            { name: 'bio', action: 'create', sourceType: 'text', sourceNullable: true, sourcePk: false, diffReason: 'Table missing in target' },
            { name: 'avatar_url', action: 'create', sourceType: 'varchar', sourceNullable: true, sourcePk: false, diffReason: 'Table missing in target' }
          ],
          syncSql: `CREATE TABLE "user_profiles" (\n  "user_id" INTEGER NOT NULL,\n  "bio" TEXT,\n  "avatar_url" VARCHAR,\n  PRIMARY KEY ("user_id")\n);`
        },
        {
          tableName: 'users',
          action: 'alter',
          sourceRowCount: 5200,
          targetRowCount: 5200,
          columns: [
            { name: 'id', action: 'identical', sourceType: 'int4', targetType: 'int4', sourceNullable: false, targetNullable: false, sourcePk: true, targetPk: true },
            { name: 'email', action: 'identical', sourceType: 'varchar', targetType: 'varchar', sourceNullable: false, targetNullable: false, sourcePk: false, targetPk: false },
            { name: 'phone', action: 'create', sourceType: 'varchar', sourceNullable: true, diffReason: 'Missing column in target' },
            { name: 'status', action: 'alter', sourceType: 'varchar', targetType: 'int4', sourceNullable: false, targetNullable: false, sourcePk: false, targetPk: false, diffReason: 'Type changed (int4 -> varchar)' },
            { name: 'is_active', action: 'identical', sourceType: 'bool', targetType: 'bool', sourceNullable: false, targetNullable: false, sourcePk: false, targetPk: false }
          ],
          syncSql: `ALTER TABLE "users" ADD COLUMN "phone" VARCHAR;\nALTER TABLE "users" ALTER COLUMN "status" TYPE VARCHAR NOT NULL;`
        },
        {
          tableName: 'orders',
          action: 'alter',
          sourceRowCount: 12400,
          targetRowCount: 12400,
          columns: [
            { name: 'id', action: 'identical', sourceType: 'int4', targetType: 'int4', sourceNullable: false, targetNullable: false, sourcePk: true, targetPk: true },
            { name: 'user_id', action: 'identical', sourceType: 'int4', targetType: 'int4', sourceNullable: false, targetNullable: false, sourcePk: false, targetPk: false },
            { name: 'notes', action: 'create', sourceType: 'text', sourceNullable: true, diffReason: 'Missing column in target' }
          ],
          syncSql: `ALTER TABLE "orders" ADD COLUMN "notes" TEXT;`
        },
        {
          tableName: 'products',
          action: 'identical',
          sourceRowCount: 340,
          targetRowCount: 340,
          columns: [
            { name: 'id', action: 'identical', sourceType: 'int4', targetType: 'int4', sourceNullable: false, targetNullable: false, sourcePk: true, targetPk: true },
            { name: 'name', action: 'identical', sourceType: 'varchar', targetType: 'varchar', sourceNullable: false, targetNullable: false, sourcePk: false, targetPk: false },
            { name: 'price', action: 'identical', sourceType: 'numeric', targetType: 'numeric', sourceNullable: false, targetNullable: false, sourcePk: false, targetPk: false }
          ],
          syncSql: ''
        }
      ],
      fullMigrationSql: `-- ===========================================================================\n-- FugDB Automated Schema Migration & Sync Script\n-- Source: Dev DB (PostgreSQL)\n-- Target: Production DB (PostgreSQL)\n-- Tables to Create: 2, Alter: 2, Drop: 0, Identical: 1\n-- ===========================================================================\n\nBEGIN;\n\n-- Table: audit_logs\nCREATE TABLE "audit_logs" (\n  "id" BIGINT NOT NULL,\n  "user_id" INTEGER NOT NULL,\n  "action" VARCHAR NOT NULL,\n  "created_at" TIMESTAMPTZ NOT NULL,\n  PRIMARY KEY ("id")\n);\n\n-- Table: user_profiles\nCREATE TABLE "user_profiles" (\n  "user_id" INTEGER NOT NULL,\n  "bio" TEXT,\n  "avatar_url" VARCHAR,\n  PRIMARY KEY ("user_id")\n);\n\n-- Table: users\nALTER TABLE "users" ADD COLUMN "phone" VARCHAR;\nALTER TABLE "users" ALTER COLUMN "status" TYPE VARCHAR NOT NULL;\n\n-- Table: orders\nALTER TABLE "orders" ADD COLUMN "notes" TEXT;\n\nCOMMIT;\n`,
      executionTimeMs: 18.4
    };
  },

  async applyMigrationScript(targetConnectionId: string, sql: string): Promise<QueryResult> {
    if (isTauri) {
      return await invoke('apply_migration_script', { targetConnectionId, sql });
    }
    await new Promise(r => setTimeout(r, 150));
    return {
      columns: [],
      rows: [],
      affectedRows: 4,
      executionTimeMs: 12.5
    };
  },

  // 5.3 Interactive SQL Scratchpad Notebooks (.fugpad)
  async saveFugpadFile(path: string, content: string): Promise<void> {
    if (isTauri) {
      return await invoke('save_fugpad_file', { path, content });
    }
    // Browser mock: save to localStorage
    try {
      localStorage.setItem(`fugpad_${path}`, content);
    } catch {}
  },

  async readFugpadFile(path: string): Promise<string> {
    if (isTauri) {
      return await invoke('read_fugpad_file', { path });
    }
    return localStorage.getItem(`fugpad_${path}`) || '{}';
  },

  async exportNotebookHtmlFile(targetPath: string, htmlContent: string): Promise<string> {
    if (isTauri) {
      return await invoke('export_notebook_html_file', { targetPath, htmlContent });
    }
    return targetPath;
  },

  async saveFileDialog(defaultName: string, filters: { name: string; extensions: string[] }[]): Promise<string | null> {
    if (isTauri) {
      const selected = await save({
        defaultPath: defaultName,
        filters
      });
      return selected;
    }
    return defaultName;
  },

  async openFileDialog(filters: { name: string; extensions: string[] }[]): Promise<string | null> {
    if (isTauri) {
      const selected = await open({
        multiple: false,
        directory: false,
        filters
      });
      return selected as string | null;
    }
    return null;
  },

  // 5.4 Redis & Key-Value Polyglot Inspector API
  async testRedisConnection(config: ConnectionConfig): Promise<{ success: boolean; message: string; latencyMs: number }> {
    if (isTauri) {
      return await invoke('test_redis_connection', { config });
    }
    await new Promise(r => setTimeout(r, 100));
    return { success: true, message: "Redis server responded 'PONG' successfully in 2 ms! (Mock)", latencyMs: 2 };
  },

  async connectRedis(config: ConnectionConfig): Promise<void> {
    if (isTauri) {
      return await invoke('connect_redis', { config });
    }
    console.log('[Mock Redis] Connected to:', config.name);
  },

  async disconnectRedis(connectionId: string): Promise<void> {
    if (isTauri) {
      return await invoke('disconnect_redis', { connectionId });
    }
    console.log('[Mock Redis] Disconnected from:', connectionId);
  },

  async scanRedisKeys(
    connectionId: string,
    pattern?: string,
    dbIndex?: number,
    cursor?: number,
    count?: number
  ): Promise<RedisScanResult> {
    if (isTauri) {
      return await invoke('scan_redis_keys', {
        connectionId,
        pattern,
        dbIndex,
        cursor,
        count
      });
    }
    // Rich mock keys
    await new Promise(r => setTimeout(r, 120));
    const mockKeys: RedisKeyItem[] = [
      { key: 'user:101:profile', keyType: 'hash', ttl: -1, size: 5, memoryBytes: 420 },
      { key: 'user:101:sessions', keyType: 'set', ttl: 86400, size: 3, memoryBytes: 180 },
      { key: 'user:102:profile', keyType: 'hash', ttl: -1, size: 4, memoryBytes: 390 },
      { key: 'auth:token:jwt_98f4a', keyType: 'string', ttl: 3540, size: 148, memoryBytes: 256 },
      { key: 'auth:rate_limit:ip_192.168.1.1', keyType: 'string', ttl: 45, size: 2, memoryBytes: 80 },
      { key: 'cache:product:latest_items', keyType: 'string', ttl: 600, size: 1240, memoryBytes: 1450 },
      { key: 'cache:config:global_features', keyType: 'string', ttl: -1, size: 420, memoryBytes: 560 },
      { key: 'queue:email_notifications', keyType: 'list', ttl: -1, size: 12, memoryBytes: 890 },
      { key: 'queue:analytics_events', keyType: 'list', ttl: -1, size: 48, memoryBytes: 3400 },
      { key: 'leaderboard:global_highscores', keyType: 'zset', ttl: -1, size: 8, memoryBytes: 640 },
      { key: 'leaderboard:weekly_challenge', keyType: 'zset', ttl: 604800, size: 5, memoryBytes: 520 },
      { key: 'stream:app_audit_logs', keyType: 'stream', ttl: -1, size: 24, memoryBytes: 4200 },
      { key: 'session:cart:guest_882', keyType: 'hash', ttl: 1800, size: 3, memoryBytes: 310 }
    ];

    const filter = pattern ? pattern.replace('*', '') : '';
    const filtered = filter
      ? mockKeys.filter(k => k.key.toLowerCase().includes(filter.toLowerCase()))
      : mockKeys;

    return {
      cursor: 0,
      keys: filtered,
      totalKeys: filtered.length,
      dbIndex: dbIndex ?? 0
    };
  },

  async getRedisKeyDetail(connectionId: string, key: string, dbIndex?: number): Promise<RedisKeyDetail> {
    if (isTauri) {
      return await invoke('get_redis_key_detail', { connectionId, key, dbIndex });
    }
    await new Promise(r => setTimeout(r, 100));

    if (key.includes('profile')) {
      return {
        key,
        keyType: 'hash',
        ttl: -1,
        memoryUsageBytes: 420,
        valueHash: {
          id: '101',
          username: 'aditya_dev',
          email: 'aditya@example.com',
          role: 'admin',
          created_at: '2026-01-15T08:30:00Z'
        }
      };
    } else if (key.includes('sessions')) {
      return {
        key,
        keyType: 'set',
        ttl: 86400,
        memoryUsageBytes: 180,
        valueSet: ['sess_9f81a', 'sess_bc209', 'sess_33dd1']
      };
    } else if (key.includes('queue')) {
      return {
        key,
        keyType: 'list',
        ttl: -1,
        memoryUsageBytes: 890,
        valueList: [
          JSON.stringify({ to: 'john@example.com', subject: 'Welcome to FugDB!', template: 'welcome_v2' }),
          JSON.stringify({ to: 'sarah@example.com', subject: 'Your invoice is ready', template: 'invoice_v1' }),
          JSON.stringify({ to: 'alex@example.com', subject: 'Security alert: New login detected', template: 'security_v1' })
        ]
      };
    } else if (key.includes('leaderboard')) {
      return {
        key,
        keyType: 'zset',
        ttl: -1,
        memoryUsageBytes: 640,
        valueZset: [
          { member: 'player:super_mario', score: 9940 },
          { member: 'player:sonic_speed', score: 8820 },
          { member: 'player:donkey_kong', score: 7650 },
          { member: 'player:zelda_link', score: 6500 }
        ]
      };
    } else if (key.includes('stream')) {
      return {
        key,
        keyType: 'stream',
        ttl: -1,
        memoryUsageBytes: 4200,
        valueStream: [
          {
            id: '1727982000000-0',
            fields: { action: 'user.login', user_id: '101', ip: '192.168.1.5', user_agent: 'FugDB Desktop v1.0' }
          },
          {
            id: '1727982045000-0',
            fields: { action: 'table.query', table: 'orders', duration_ms: '14.2', status: '200' }
          },
          {
            id: '1727982120000-0',
            fields: { action: 'data.export', format: 'csv', total_rows: '15000', filename: 'sales_2026.csv' }
          }
        ]
      };
    }

    return {
      key,
      keyType: 'string',
      ttl: 3600,
      memoryUsageBytes: 256,
      valueString: '{"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...", "expiresIn": 3600, "scope": "read:all write:all"}'
    };
  },

  async setRedisString(
    connectionId: string,
    key: string,
    value: string,
    ttl?: number,
    dbIndex?: number
  ): Promise<void> {
    if (isTauri) {
      return await invoke('set_redis_string', { connectionId, key, value, ttl, dbIndex });
    }
    console.log('[Mock Redis] SET', key, value, 'TTL:', ttl);
  },

  async setRedisHashField(
    connectionId: string,
    key: string,
    field: string,
    value: string,
    dbIndex?: number
  ): Promise<void> {
    if (isTauri) {
      return await invoke('set_redis_hash_field', { connectionId, key, field, value, dbIndex });
    }
    console.log('[Mock Redis] HSET', key, field, value);
  },

  async deleteRedisHashField(
    connectionId: string,
    key: string,
    field: string,
    dbIndex?: number
  ): Promise<void> {
    if (isTauri) {
      return await invoke('delete_redis_hash_field', { connectionId, key, field, dbIndex });
    }
    console.log('[Mock Redis] HDEL', key, field);
  },

  async pushRedisListElement(
    connectionId: string,
    key: string,
    value: string,
    position: 'left' | 'right',
    dbIndex?: number
  ): Promise<void> {
    if (isTauri) {
      return await invoke('push_redis_list_element', { connectionId, key, value, position, dbIndex });
    }
    console.log('[Mock Redis] PUSH', position, key, value);
  },

  async removeRedisListElement(
    connectionId: string,
    key: string,
    value: string,
    dbIndex?: number
  ): Promise<void> {
    if (isTauri) {
      return await invoke('remove_redis_list_element', { connectionId, key, value, dbIndex });
    }
    console.log('[Mock Redis] LREM', key, value);
  },

  async addRedisSetMember(
    connectionId: string,
    key: string,
    member: string,
    dbIndex?: number
  ): Promise<void> {
    if (isTauri) {
      return await invoke('add_redis_set_member', { connectionId, key, member, dbIndex });
    }
    console.log('[Mock Redis] SADD', key, member);
  },

  async removeRedisSetMember(
    connectionId: string,
    key: string,
    member: string,
    dbIndex?: number
  ): Promise<void> {
    if (isTauri) {
      return await invoke('remove_redis_set_member', { connectionId, key, member, dbIndex });
    }
    console.log('[Mock Redis] SREM', key, member);
  },

  async addRedisZSetMember(
    connectionId: string,
    key: string,
    member: string,
    score: number,
    dbIndex?: number
  ): Promise<void> {
    if (isTauri) {
      return await invoke('add_redis_zset_member', { connectionId, key, member, score, dbIndex });
    }
    console.log('[Mock Redis] ZADD', key, score, member);
  },

  async removeRedisZSetMember(
    connectionId: string,
    key: string,
    member: string,
    dbIndex?: number
  ): Promise<void> {
    if (isTauri) {
      return await invoke('remove_redis_zset_member', { connectionId, key, member, dbIndex });
    }
    console.log('[Mock Redis] ZREM', key, member);
  },

  async setRedisKeyTtl(
    connectionId: string,
    key: string,
    ttl: number,
    dbIndex?: number
  ): Promise<void> {
    if (isTauri) {
      return await invoke('set_redis_key_ttl', { connectionId, key, ttl, dbIndex });
    }
    console.log('[Mock Redis] EXPIRE / PERSIST', key, ttl);
  },

  async deleteRedisKeys(
    connectionId: string,
    keys: string[],
    dbIndex?: number
  ): Promise<number> {
    if (isTauri) {
      return await invoke('delete_redis_keys', { connectionId, keys, dbIndex });
    }
    console.log('[Mock Redis] DEL', keys);
    return keys.length;
  },

  async renameRedisKey(
    connectionId: string,
    oldKey: string,
    newKey: string,
    dbIndex?: number
  ): Promise<void> {
    if (isTauri) {
      return await invoke('rename_redis_key', { connectionId, oldKey, newKey, dbIndex });
    }
    console.log('[Mock Redis] RENAME', oldKey, '->', newKey);
  },

  async getRedisServerInfo(connectionId: string): Promise<RedisServerInfo> {
    if (isTauri) {
      return await invoke('get_redis_server_info', { connectionId });
    }
    await new Promise(r => setTimeout(r, 80));
    return {
      version: '7.2.4',
      os: 'Darwin 23.4.0 arm64',
      uptimeSeconds: 384920,
      connectedClients: 4,
      usedMemoryHuman: '14.28M',
      usedMemoryPeakHuman: '22.80M',
      totalKeys: 42,
      rawInfo: {
        redis_version: '7.2.4',
        os: 'Darwin 23.4.0 arm64',
        tcp_port: '6379',
        uptime_in_days: '4',
        connected_clients: '4',
        used_memory_human: '14.28M',
        used_memory_peak_human: '22.80M',
        maxmemory_human: '2.00G',
        rdb_last_bgsave_status: 'ok',
        instantaneous_ops_per_sec: '45'
      }
    };
  },

  async executeRedisCliCommand(
    connectionId: string,
    commandLine: string,
    dbIndex?: number
  ): Promise<RedisCliResponse> {
    if (isTauri) {
      return await invoke('execute_redis_cli_command', { connectionId, commandLine, dbIndex });
    }
    await new Promise(r => setTimeout(r, 60));
    const trimmed = commandLine.trim();
    if (trimmed.toUpperCase() === 'PING') {
      return { command: commandLine, response: 'PONG', responseType: 'status', durationMs: 0.8 };
    }
    if (trimmed.toUpperCase().startsWith('GET ')) {
      return { command: commandLine, response: '"sample_mock_value"', responseType: 'string', durationMs: 1.2 };
    }
    if (trimmed.toUpperCase().startsWith('KEYS ')) {
      return {
        command: commandLine,
        response: '1) "user:101:profile"\n2) "user:101:sessions"\n3) "queue:email_notifications"',
        responseType: 'array',
        durationMs: 2.1
      };
    }
    return {
      command: commandLine,
      response: 'OK',
      responseType: 'status',
      durationMs: 1.0
    };
  },

  async flushRedisDb(connectionId: string, dbIndex?: number): Promise<void> {
    if (isTauri) {
      return await invoke('flush_redis_db', { connectionId, dbIndex });
    }
    console.log('[Mock Redis] FLUSHDB on db', dbIndex);
  }
};

