use chrono::Local;
use crate::models::schema::SchemaTree;

pub fn generate_markdown_dictionary(tree: &SchemaTree, conn_name: &str, driver: &str) -> String {
    let now = Local::now().format("%Y-%m-%d %H:%M:%S").to_string();
    let total_tables = tree.tables.len();
    let total_relations = tree.relations.len();
    let total_columns: usize = tree.tables.iter().map(|t| t.columns.len()).sum();

    let mut md = String::new();

    // 1. Header
    md.push_str(&format!("# 📚 Database Schema Documentation: {}\n\n", conn_name));
    md.push_str("> **Generated by FugDB 1-Click Data Dictionary Engine**  \n");
    md.push_str(&format!(
        "> **Database:** `{}` | **Driver Engine:** `{}` | **Generated on:** `{}`  \n",
        tree.current_database, driver, now
    ));
    md.push_str(&format!(
        "> **Summary:** `{} Tables / Views` • `{} Columns` • `{} Foreign Key Relations`\n\n",
        total_tables, total_columns, total_relations
    ));
    md.push_str("---\n\n");

    // 2. Table of Contents
    md.push_str("## 📑 Table of Contents\n\n");
    for (idx, tbl) in tree.tables.iter().enumerate() {
        let full_name = format!("{}.{}", tbl.schema, tbl.name);
        let slug = full_name.replace('.', "").to_lowercase();
        let rows_badge = match tbl.row_count_estimate {
            Some(c) => format!("~{} rows", c),
            None => "table".into(),
        };
        md.push_str(&format!(
            "{}. [{}] (#{}) — *{} ({})*\n",
            idx + 1,
            full_name,
            slug,
            tbl.table_type,
            rows_badge
        ));
    }
    md.push_str("\n---\n\n");

    // 3. Detailed Tables Section
    md.push_str("## 🗄️ Tables & Entities\n\n");
    for tbl in &tree.tables {
        let full_name = format!("{}.{}", tbl.schema, tbl.name);
        let slug = full_name.replace('.', "").to_lowercase();
        let rows_str = match tbl.row_count_estimate {
            Some(c) => format!("~{} rows", c),
            None => "N/A".into(),
        };

        md.push_str(&format!("<a id=\"{}\"></a>\n\n", slug));
        md.push_str(&format!("### `{}`\n\n", full_name));
        md.push_str(&format!("* **Schema:** `{}`\n", tbl.schema));
        md.push_str(&format!("* **Type:** `{}`\n", tbl.table_type.to_uppercase()));
        md.push_str(&format!("* **Estimated Row Count:** `{}`\n", rows_str));
        md.push_str(&format!("* **Total Columns:** `{}`\n\n", tbl.columns.len()));

        md.push_str("| # | Column Name | Data Type | Key | Nullable | Notes |\n");
        md.push_str("|---|---|---|---|---|---|\n");

        for (c_idx, col) in tbl.columns.iter().enumerate() {
            let key_badge = if col.is_primary_key && col.is_foreign_key {
                "🔑 PK, 🔗 FK"
            } else if col.is_primary_key {
                "🔑 PK"
            } else if col.is_foreign_key {
                "🔗 FK"
            } else {
                "-"
            };

            let null_str = if col.nullable { "✅ NULL" } else { "❌ NOT NULL" };
            
            // Check if column is a foreign key to find reference target
            let fk_target = tree.relations.iter().find(|r| {
                (r.from_table == tbl.name || r.from_table == full_name) && r.from_column == col.name
            });

            let notes = match fk_target {
                Some(rel) => format!("References `{}.{}`", rel.to_table, rel.to_column),
                None => {
                    if col.is_primary_key {
                        "Primary Key identifier".into()
                    } else {
                        "-".into()
                    }
                }
            };

            md.push_str(&format!(
                "| {} | **`{}`** | `{}` | {} | {} | {} |\n",
                c_idx + 1,
                col.name,
                col.data_type,
                key_badge,
                null_str,
                notes
            ));
        }

        // Table specific foreign keys
        let table_fks: Vec<_> = tree.relations.iter().filter(|r| {
            r.from_table == tbl.name || r.from_table == full_name
        }).collect();

        if !table_fks.is_empty() {
            md.push_str("\n**Foreign Key Constraints:**\n\n");
            for fk in table_fks {
                md.push_str(&format!(
                    "- `{}.{}` ➔ `{}.{}` *({})*\n",
                    tbl.name, fk.from_column, fk.to_table, fk.to_column, fk.id
                ));
            }
        }

        md.push_str("\n[⬆ Back to Top](#table-of-contents)\n\n---\n\n");
    }

    // 4. Global Entity Relationships
    if !tree.relations.is_empty() {
        md.push_str("## 🔗 Global Entity Relationships\n\n");
        md.push_str("| Constraint ID | Source Table & Column | Target Table & Column |\n");
        md.push_str("|---|---|---|\n");
        for rel in &tree.relations {
            md.push_str(&format!(
                "| `{}` | `{}.{}` | `{}.{}` |\n",
                rel.id, rel.from_table, rel.from_column, rel.to_table, rel.to_column
            ));
        }
        md.push_str("\n---\n\n");
    }

    md.push_str("\n*Generated with ❤️ by [FugDB](https://fugdb.dev) — Ultra-Fast Multi-Database Client*\n");
    md
}

pub fn generate_html_dictionary(tree: &SchemaTree, conn_name: &str, driver: &str) -> String {
    let now = Local::now().format("%Y-%m-%d %H:%M:%S").to_string();
    let total_tables = tree.tables.len();
    let total_relations = tree.relations.len();
    let total_columns: usize = tree.tables.iter().map(|t| t.columns.len()).sum();

    let mut html = String::new();

    html.push_str(r#"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Data Dictionary - "#);
    html.push_str(conn_name);
    html.push_str(r#"</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600&display=swap" rel="stylesheet">
  <style>
    :root {
      --bg: #0f172a;
      --card-bg: #1e293b;
      --card-border: #334155;
      --text: #f8fafc;
      --text-muted: #94a3b8;
      --primary: #6366f1;
      --primary-light: #818cf8;
      --badge-pk: #fef08a;
      --badge-pk-text: #854d0e;
      --badge-fk: #e0e7ff;
      --badge-fk-text: #3730a3;
      --badge-null: #dcfce7;
      --badge-null-text: #166534;
      --badge-notnull: #fee2e2;
      --badge-notnull-text: #991b1b;
    }
    @media (prefers-color-scheme: light) {
      :root {
        --bg: #f8fafc;
        --card-bg: #ffffff;
        --card-border: #e2e8f0;
        --text: #0f172a;
        --text-muted: #64748b;
      }
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
      background-color: var(--bg);
      color: var(--text);
      line-height: 1.6;
      padding: 2rem 1rem;
    }
    .container { max-width: 1100px; margin: 0 auto; }
    .header {
      background: var(--card-bg);
      border: 1px solid var(--card-border);
      border-radius: 1rem;
      padding: 2rem;
      margin-bottom: 2rem;
      box-shadow: 0 4px 20px -2px rgba(0,0,0,0.1);
    }
    .header h1 { font-size: 1.75rem; font-weight: 800; margin-bottom: 0.5rem; display: flex; align-items: center; gap: 0.75rem; }
    .header p { color: var(--text-muted); font-size: 0.875rem; margin-bottom: 1.25rem; }
    .stats-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
      gap: 1rem;
      margin-top: 1rem;
    }
    .stat-card {
      background: rgba(99, 102, 241, 0.08);
      border: 1px solid rgba(99, 102, 241, 0.2);
      border-radius: 0.75rem;
      padding: 1rem;
      text-align: center;
    }
    .stat-val { font-size: 1.5rem; font-weight: 800; color: var(--primary-light); }
    .stat-lbl { font-size: 0.75rem; font-weight: 600; color: var(--text-muted); text-transform: uppercase; }
    .search-box {
      margin: 1.5rem 0;
      position: sticky;
      top: 1rem;
      z-index: 30;
    }
    .search-input {
      width: 100%;
      padding: 0.875rem 1.25rem;
      background: var(--card-bg);
      border: 2px solid var(--card-border);
      border-radius: 0.75rem;
      color: var(--text);
      font-size: 0.95rem;
      font-family: inherit;
      box-shadow: 0 10px 25px -5px rgba(0,0,0,0.15);
      outline: none;
      transition: border-color 0.2s;
    }
    .search-input:focus { border-color: var(--primary); }
    .table-card {
      background: var(--card-bg);
      border: 1px solid var(--card-border);
      border-radius: 1rem;
      margin-bottom: 2rem;
      overflow: hidden;
      box-shadow: 0 4px 15px -2px rgba(0,0,0,0.05);
    }
    .table-header {
      padding: 1.25rem 1.5rem;
      background: rgba(99, 102, 241, 0.04);
      border-bottom: 1px solid var(--card-border);
      display: flex;
      justify-content: space-between;
      align-items: center;
      flex-wrap: wrap;
      gap: 0.5rem;
    }
    .table-title { font-family: 'JetBrains Mono', monospace; font-size: 1.1rem; font-weight: 700; }
    .badge {
      display: inline-flex;
      align-items: center;
      padding: 0.25rem 0.6rem;
      border-radius: 0.375rem;
      font-size: 0.75rem;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.025em;
    }
    .badge-pk { background: var(--badge-pk); color: var(--badge-pk-text); }
    .badge-fk { background: var(--badge-fk); color: var(--badge-fk-text); }
    .badge-null { background: var(--badge-null); color: var(--badge-null-text); }
    .badge-notnull { background: var(--badge-notnull); color: var(--badge-notnull-text); }
    .data-table {
      width: 100%;
      border-collapse: collapse;
      text-align: left;
      font-size: 0.875rem;
    }
    .data-table th {
      background: rgba(0,0,0,0.04);
      padding: 0.75rem 1.25rem;
      font-weight: 600;
      font-size: 0.75rem;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: var(--text-muted);
      border-bottom: 1px solid var(--card-border);
    }
    .data-table td {
      padding: 0.875rem 1.25rem;
      border-bottom: 1px solid var(--card-border);
    }
    .data-table tr:last-child td { border-bottom: none; }
    .col-name { font-family: 'JetBrains Mono', monospace; font-weight: 600; }
    .col-type { font-family: 'JetBrains Mono', monospace; color: var(--primary-light); }
    .footer { text-align: center; font-size: 0.8rem; color: var(--text-muted); margin-top: 3rem; }
    @media print {
      body { background: white; color: black; padding: 0; }
      .search-box { display: none; }
      .table-card { break-inside: avoid; border: 1px solid #ccc; box-shadow: none; margin-bottom: 1.5rem; }
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>📚 Database Documentation: "#);
    html.push_str(conn_name);
    html.push_str(r#"</h1>
      <p>Generated by <strong>FugDB 1-Click Data Dictionary Engine</strong> on "#);
    html.push_str(&now);
    html.push_str(r#"</p>
      <div class="stats-grid">
        <div class="stat-card">
          <div class="stat-val">"#);
    html.push_str(&total_tables.to_string());
    html.push_str(r#"</div>
          <div class="stat-lbl">Tables / Views</div>
        </div>
        <div class="stat-card">
          <div class="stat-val">"#);
    html.push_str(&total_columns.to_string());
    html.push_str(r#"</div>
          <div class="stat-lbl">Columns</div>
        </div>
        <div class="stat-card">
          <div class="stat-val">"#);
    html.push_str(&total_relations.to_string());
    html.push_str(r#"</div>
          <div class="stat-lbl">FK Relations</div>
        </div>
        <div class="stat-card">
          <div class="stat-val">"#);
    html.push_str(driver);
    html.push_str(r#"</div>
          <div class="stat-lbl">Engine Driver</div>
        </div>
      </div>
    </div>

    <div class="search-box">
      <input type="text" id="search" class="search-input" placeholder="🔍 Instant search tables or column names..." oninput="filterTables(this.value)">
    </div>

    <div id="tables-container">"#);

    for tbl in &tree.tables {
        let full_name = format!("{}.{}", tbl.schema, tbl.name);
        let rows_str = match tbl.row_count_estimate {
            Some(c) => format!("~{} rows", c),
            None => "N/A".into(),
        };

        html.push_str(&format!(
            r#"<div class="table-card" data-table="{}">
        <div class="table-header">
          <div>
            <span class="table-title">{}</span>
            <span class="badge" style="background: rgba(99,102,241,0.15); color: var(--primary-light); margin-left: 0.5rem;">{}</span>
          </div>
          <div style="font-size: 0.8rem; color: var(--text-muted);">{} • {} columns</div>
        </div>
        <div style="overflow-x: auto;">
          <table class="data-table">
            <thead>
              <tr>
                <th>#</th>
                <th>Column Name</th>
                <th>Data Type</th>
                <th>Key</th>
                <th>Nullable</th>
                <th>Reference / Description</th>
              </tr>
            </thead>
            <tbody>"#,
            full_name.to_lowercase(),
            full_name,
            tbl.table_type.to_uppercase(),
            rows_str,
            tbl.columns.len()
        ));

        for (c_idx, col) in tbl.columns.iter().enumerate() {
            let key_badge = if col.is_primary_key && col.is_foreign_key {
                r#"<span class="badge badge-pk">PK</span> <span class="badge badge-fk">FK</span>"#
            } else if col.is_primary_key {
                r#"<span class="badge badge-pk">PK</span>"#
            } else if col.is_foreign_key {
                r#"<span class="badge badge-fk">FK</span>"#
            } else {
                "-"
            };

            let null_badge = if col.nullable {
                r#"<span class="badge badge-null">NULL</span>"#
            } else {
                r#"<span class="badge badge-notnull">NOT NULL</span>"#
            };

            let fk_target = tree.relations.iter().find(|r| {
                (r.from_table == tbl.name || r.from_table == full_name) && r.from_column == col.name
            });

            let desc = match fk_target {
                Some(rel) => format!("🔗 References <code>{}.{}</code>", rel.to_table, rel.to_column),
                None => {
                    if col.is_primary_key {
                        "Primary Key Identifier".into()
                    } else {
                        "-".into()
                    }
                }
            };

            html.push_str(&format!(
                r#"<tr>
                <td style="color: var(--text-muted); font-size: 0.75rem;">{}</td>
                <td class="col-name">{}</td>
                <td class="col-type">{}</td>
                <td>{}</td>
                <td>{}</td>
                <td style="color: var(--text-muted); font-size: 0.8rem;">{}</td>
              </tr>"#,
                c_idx + 1,
                col.name,
                col.data_type,
                key_badge,
                null_badge,
                desc
            ));
        }

        html.push_str(r#"</tbody>
          </table>
        </div>
      </div>"#);
    }

    html.push_str(r#"</div>

    <div class="footer">
      Generated with ❤️ by <a href="https://fugdb.dev" target="_blank" style="color: var(--primary-light); text-decoration: none; font-weight: 600;">FugDB</a> — Ultra-Fast Multi-Database Client
    </div>
  </div>

  <script>
    function filterTables(query) {
      const q = query.toLowerCase().trim();
      const cards = document.querySelectorAll('.table-card');
      cards.forEach(card => {
        const text = card.textContent.toLowerCase();
        if (!q || text.includes(q)) {
          card.style.display = 'block';
        } else {
          card.style.display = 'none';
        }
      });
    }
  </script>
</body>
</html>"#);

    html
}

pub fn generate_json_dictionary(tree: &SchemaTree, conn_name: &str, driver: &str) -> String {
    let now = Local::now().format("%Y-%m-%d %H:%M:%S").to_string();
    let payload = serde_json::json!({
        "generatedAt": now,
        "generator": "FugDB 1-Click Data Dictionary",
        "connectionName": conn_name,
        "driver": driver,
        "database": tree.current_database,
        "stats": {
            "totalTables": tree.tables.len(),
            "totalColumns": tree.tables.iter().map(|t| t.columns.len()).sum::<usize>(),
            "totalRelations": tree.relations.len(),
        },
        "tables": tree.tables,
        "relations": tree.relations,
    });

    serde_json::to_string_pretty(&payload).unwrap_or_else(|_| "{}".into())
}
